
[Getting Django Set Up Using a Functional Test ](https://www.obeythetestinggoat.com/book/chapter_01.html)

Obey the Testing Goat! Do Nothing Until You Have a Test

When you’re doing TDD, you always have the Testing Goat inside you—​single-minded as goats are—​bleating “Test first, test first!”

In TDD the first step is always the same: write a test.


```
(venv) 20/05/29 3:31:27 kvogel-macbook-2018:~/Projects/python/tdd/testinggoat ±(master) ✗
❯ python
Python 3.6.10 (default, Dec 21 2019, 11:40:12)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
>>> import django
>>> django.get_version()
'1.11.29'
❯ which django-admin.py
/Users/kvogel/Projects/python/tdd/testinggoat/venv/bin/django-admin.py
❯ django-admin.py startproject superlists .
```


the main thing to notice is manage.py. That’s Django’s Swiss Army knife, and one of the things it can do is run a development server. 


[firefox - Selenium WebDriverException: Reached error page](https://stackoverflow.com/questions/43812991/selenium-webdriverexception-reached-error-page)
found an old comment by me from 2016, and added this:
>This worked for me. I had the virtualenv activated, django server running, but still got the error. Firefox starts up, tries to access http://localhost:8000, and fails, so selenium raises an exception. But when I refresh the browser manually, the page loads. If I change the code to do self.browser.get('http://127.0.0.1:8000'), as you suggest, the page loads first time, no exception is thrown and the test passes. Weird. I wonder if the same happens with Chrome instead of Firefox? –

